### ISSUE TITLE
testing code

### ISSUE THREAD

**Issue by finnp** [nodeschool/workshoppers#14]
Maybe starting with general assertions and then use a library like https://github.com/substack/tape .

I also thought that it might be cool to actually have a workshop, where you test the code you have written in another workshop. But I am not sure which lesson would be appropriate for that (should be something basic like `learnyounode`).

Ideas for Topics:
* Assertions
* Testing synchronous functions
* Testing with callbacks

**Comment by tomgco** [comment]
I have also just started the same thing https://github.com/tomgco/tapeshopper, albeit slightly different - @finnp are you still working on this?

**Comment by finnp** [comment]
The workshopper is published on the website now. If you have any additions, go ahead and PR to it, if you want.
