### ISSUE TITLE
ES6 generators workshooper

### ISSUE THREAD

**Issue by isRuslan** [nodeschool/workshoppers#29]
Hi everyone.
I've made [learn-generators](https://github.com/isRuslan/learn-generators) workshopper.
Any issues, feedback or promotions would be welcome. Thanks!

**Comment by mikeal** [comment]
Maybe the website should have an "ES6/io.js" section so that people don't try to run these in this node.js.

**Comment by isRuslan** [comment]
Yeap, this workshopper have been tested with iojs and it worked well.
Readme updated.
